# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae7ff4d1559a7802e6bfd9145cc384ccf6a951b26567131ecb6549863a9bccbe5e9e3275b77c04acca283f858d9d6d57b4ae6b1f10697b6bb7abd44f34e2c72f

test:
  secret_key_base: 56fe34e3e886f877e8adc3cc30ffac5d2b85d9dbc93c31153a24d681f9f831f5aa56e157ddfd04b5ac1c9f5cb62c27e84e9f4e7758b67a311c55a7a11d791aa5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
